image:
  name: gcr.io/kaniko-project/executor:debug-v0.16.0
  entrypoint: [""]

stages:
  - mirror
  - build_base
  - build
  - build_singularity

mirror repository:
  image: $CI_REGISTRY_IMAGE:base
  stage: mirror
  allow_failure: true
  variables:
    REPO: "git@github.com:quantum-tinkerer/research-docker.git"
  before_script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  after_script:
    - rm -rf ~/.ssh
  script:
    - ORIGIN_URL=$(git config --get remote.origin.url)
    - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
    - git push --mirror $REPO

.build base image:
    stage: build_base
    before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    script:
      - /kaniko/executor
        --context $CI_PROJECT_DIR/base_image
        --dockerfile $CI_PROJECT_DIR/base_image/Dockerfile
        --destination $CI_REGISTRY_IMAGE:base
        --reproducible

build base image:master:
  extends: .build base image
  only:
    refs:
      - master
      - schedules
    changes:
      - base_image/**/*

build base image:scheduled:
  extends: .build base image
  only:
    refs:
      - schedules

build base image:manual:
  extends: .build base image
  when: manual

build image:
  stage: build
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - branches
      - tags
  before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - '[[ "$CI_COMMIT_REF_SLUG" == "master" ]] && export CI_REF="latest" || export CI_REF="$CI_COMMIT_REF_SLUG"'
  script:
    - echo "CI_REF=$CI_REF" >> build.env
    - /kaniko/executor
      --context $CI_PROJECT_DIR/main_image
      --dockerfile $CI_PROJECT_DIR/main_image/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_REF
      --reproducible
  artifacts:
    reports:
      dotenv: build.env

build singularity image:
  stage: build_singularity
  image:
    name: quay.io/singularity/singularity:v3.5.3
    entrypoint: [""]
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - master@qt/research-docker
      - staging@qt/research-docker
      - singularity@qt/research-docker  # TEMP
  script:
    - singularity build research-docker.simg docker://$CI_REGISTRY_IMAGE:$CI_REF
  needs:
    - job: build image
      artifacts: true
  artifacts:
    paths:
      - research-docker.simg
    # images are rebuilt every week, so this should be enough to keep them permanently
    expire_in: 2 weeks