image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build
  - build_singularity

build image:
  stage: build
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - branches
      - tags
  before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - '[[ "$CI_COMMIT_REF_SLUG" == "master" ]] && export CI_REF="latest" || export CI_REF="$CI_COMMIT_REF_SLUG"'
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_REF
      --build-arg GITLAB_API_TOKEN=$GITLAB_API_TOKEN
      --build-arg CI_PIPELINE_ID=$CI_PIPELINE_ID
      --reproducible
      --cache=true
    - /busybox/sed -e "s%{{ docker_container_name }}%$CI_REGISTRY_IMAGE:$CI_REF%g" Singularity.j2 > Singularity
  artifacts:
    paths:
      - Singularity

build singularity image:
  stage: build_singularity
  image:
    name: quay.io/singularity/singularity:v3.5.3
    entrypoint: [""]
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - master@qt/research-docker
      - staging@qt/research-docker
  before_script:
    - mkdir -p build
  script:
    - cp Singularity build/Singularity
    - cd build && /bin/bash ../.ci/build_singularity.sh Singularity
  needs: ["build image"]
  artifacts:
    paths:
      - build/Singularity
      - build/Singularity.simg
