stages:
  - mirror
  - build_base
  - build

mirror repository:
  stage: mirror
  allow_failure: true
  variables:
    REPO: "git@github.com:quantum-tinkerer/research-docker.git"
  before_script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  after_script:
    - rm -rf ~/.ssh
  script:
    - ORIGIN_URL=$(git config --get remote.origin.url)
    - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
    - git push --mirror $REPO

.build base image:
    stage: build_base
    image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
    before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    script:
      - /kaniko/executor
        --context $CI_PROJECT_DIR/base_image
        --dockerfile $CI_PROJECT_DIR/base_image/Dockerfile
        --destination $CI_REGISTRY_IMAGE:base

# FIXME: remove this before merge
build base image:test:
  extends: .build base image
  only:
    refs:
      - enh/split_images

build base image:master:
  extends: .build base image
  only:
    refs:
      - master
      - schedules
    changes:
      - base_image/**/*

build base image:scheduled:
  extends: .build base image
  only:
    refs:
      - schedules

build image:
  stage: build
  image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
  only:
    # To ensure that CI_COMMIT_REF_SLUG exists
    refs:
      - branches
      - tags
  before_script:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - '[[ "$CI_COMMIT_REF_SLUG" == "master" ]] && export CI_REF="latest" || export CI_REF="$CI_COMMIT_REF_SLUG"'
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR/main_image
      --dockerfile $CI_PROJECT_DIR/main_image/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_REF
