name: dev
channels:
  - kwant
  - ioam
  - conda-forge
dependencies:
  # general numerics
  - python=3.6
  - anaconda
  - kwant=dev
  - discretizer=0.4*
  - cython
  - libgcc=5.2.0
  # fenics
  - fenics
  - mshr
  # plotting and serialization
  - deepdish
  - plotly
  # parallell computing
  - dill
  - distributed
  - hpc05
  - ipyparallel
  # other
  - line_profiler
  - boost
  - feedparser
  - pytest-flakes
  - python-graphviz
  - xarray
  - pillow
  - ipykernel>=4.8*  # needed for adaptive
  - jupyter_client>=5.2.2  # needed for adaptive
  - ipywidgets
  - pip:
    - git+https://github.com/ioam/holoviews.git
    - git+https://github.com/python-adaptive/adaptive.git
