name: dev
channels:
  - kwant
  - ioam
  - conda-forge
dependencies:
  # general numerics
  - python
  - anaconda
  - kwant
  - cython
  # plotting and serialization
  - deepdish
  - plotly
  # parallell computing
  - dill
  - distributed
  - hpc05
  - ipyparallel
  # other
  - line_profiler
  - feedparser
  - pytest-flakes
  - python-graphviz
  - xarray
  - pillow
  - ipywidgets
  - pip:
    - git+https://github.com/ioam/holoviews.git
    - git+https://github.com/python-adaptive/adaptive.git
